@token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3NDJkMzg2MS00NWNlLTQzNmUtOTc1OS0wYTgyZWJhZjg2ZDIiLCJzdWIiOiIwNmI3YjE1NS00YzJjLTQ2MWEtYTAyNy01MzhkYzAzZDMyYTIiLCJlbWFpbCI6WyJ0ZXN0b3ZfdGVzb3R2IiwidGVzdG92X3VzZXJvdkBnbWFpbC5jb20iXSwibmFtZWlkIjoiMDZiN2IxNTUtNGMyYy00NjFhLWEwMjctNTM4ZGMwM2QzMmEyIiwidW5pcXVlX25hbWUiOiJ0ZXN0b3ZfdGVzb3R2IiwibmJmIjoxNzQxMTgzNDgyLCJleHAiOjE3NDExODQzODIsImlhdCI6MTc0MTE4MzQ4MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTA1OCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwNTgifQ.80619h4axVVowud_3w-dgOeO5bpXMYF9me5MDuWbxAs"
@refreshToken = "ayyGVflGf0SvHAohPsv/fQ=="  

POST http://localhost:5058/api/authentication/refreshToken
Content-Type: application/json
Authorization: {{token}}

{
    "jwtToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwMTEzOTY1My1mM2ZmLTQ5NGQtYmQ2OS1lMzdjYWRkM2IyY2EiLCJzdWIiOiIwNmI3YjE1NS00YzJjLTQ2MWEtYTAyNy01MzhkYzAzZDMyYTIiLCJlbWFpbCI6WyJ0ZXN0b3ZfdGVzb3R2IiwidGVzdG92X3VzZXJvdkBnbWFpbC5jb20iXSwibmFtZWlkIjoiMDZiN2IxNTUtNGMyYy00NjFhLWEwMjctNTM4ZGMwM2QzMmEyIiwidW5pcXVlX25hbWUiOiJ0ZXN0b3ZfdGVzb3R2IiwibmJmIjoxNzQxMTgzMTk5LCJleHAiOjE3NDExODQwOTksImlhdCI6MTc0MTE4MzE5OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTA1OCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwNTgifQ.-AVQfDKhQf2WOhim-kQRJLHaAS9uOmfnMNg9AavRleg",
    "refreshToken": "jqdZ47Q760mVZ6RWlRMBSA=="
}